### ISSUE TITLE
Sigpy won't build with `pip install .`

### ISSUE THREAD

**Issue by wtclarke** [mikgroup/sigpy#127]
**Describe the bug**
When trying to build the version of sigpy on this GitHub repository using `pip install .` an error is returned `ModuleNotFoundError: No module named 'numpy'`. This is despite the active environment having `numpy` installed.

This arises from:
1. `pip install .` will use an isolated build environment when building a wheel, not the environment you call it from. Described in the pip [documentation](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-isolation) for packages with a `pyproject.toml` file.
2. sigpy implicitly requires numpy to be built (because of [this](https://github.com/mikgroup/sigpy/blob/main/setup.py#L5) import statement in setup.py)
3. sigpy has not listed numpy (nor anything else) as a build-time requirement

**To Reproduce**
1.  create an appropriate environment for sigpy (e.g `conda create -n sigpy -c conda-forge python=3.10 numpy`) and activate it.
2. `git clone https://github.com/mikgroup/sigpy.git`
3. `cd sigpy`
4. `pip install .`

**Expected behavior**
The wheel should be built and the package installed into the environment

**Error**
```
pip install .                  
Processing /Users/wclarke/tmp/sigpy
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/wclarke/miniconda3/envs/spice/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/wclarke/miniconda3/envs/spice/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/wclarke/miniconda3/envs/spice/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/nn/v2nq0rss0yz3zzf069f84hxw0000gt/T/pip-build-env-dfj4yafw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/nn/v2nq0rss0yz3zzf069f84hxw0000gt/T/pip-build-env-dfj4yafw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/nn/v2nq0rss0yz3zzf069f84hxw0000gt/T/pip-build-env-dfj4yafw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/nn/v2nq0rss0yz3zzf069f84hxw0000gt/T/pip-build-env-dfj4yafw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "/Users/wclarke/tmp/sigpy/sigpy/__init__.py", line 11, in <module>
          from sigpy import (
        File "/Users/wclarke/tmp/sigpy/sigpy/alg.py", line 6, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Desktop (please complete the following information):**
 - OS: macos

**Comment by kmjohnson3** [comment]
We recently also had this issue and rewrote the pyproject.toml to replace the setup files. I'll issue a pull request for the fix.

**Comment by sidward** [comment]
Thank you for the PR and apologies for not catching it. I just merged it -- if there are issues still please reopen!
