### ISSUE TITLE
RuntimeError: No available algorithm found.

### ISSUE THREAD

**Issue by ltorres6** [mikgroup/sigpy#62]
I updated sigpy to 0.1.21 (from 0.1.18) and now I can't run the JsenseRecon app on the GPU. I've tried downgrading sigpy again, and installing in a fresh environment and still get the same error, so I'm stuck, even though it was working fine before I upgraded (via conda). Maybe someone can help me figure out what's going on.

Code used to reproduce:
```
import numpy as np
import sigpy as sp
import sigpy.mri as mri
import sigpy.plot as plt

dataInDir = "/home/ltorres/data/forMatt/"
ksp = np.load("{}ksp.npy".format(dataInDir))
coord = np.load("{}coord.npy".format(dataInDir))
dcf = np.load("{}dcf.npy".format(dataInDir))

device = 0
ksp = sp.to_device(ksp, device)
coord = sp.to_device(coord, device)
dcf = sp.to_device(dcf, device)
mps = mri.app.JsenseRecon(
    ksp,
    coord=coord,
    weights=dcf,
    device=device,
).run()
```

Resulting Error:
```
JsenseRecon:   0%|                                                         | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 95, in apply
    output = self._apply(input)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 1657, in _apply
    multi_channel=self.multi_channel)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/conv.py", line 143, in convolve_filter_adjoint
    multi_channel=multi_channel)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/conv.py", line 311, in _complex
    outputr = func(data1r, data2r, *kargs, **kwargs)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/conv.py", line 412, in _convolve_filter_adjoint_cuda
    tensor_core=tensor_core)
  File "cupy/cudnn.pyx", line 1817, in cupy.cudnn.convolution_backward_filter
  File "cupy/cudnn.pyx", line 1469, in cupy.cudnn._find_algorithm_bwd_filter
RuntimeError: No available algorithm found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 95, in apply
    output = self._apply(input)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 362, in _apply
    output = linop(output)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 122, in __call__
    return self.__mul__(input)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 131, in __mul__
    return self.apply(input)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 98, in apply
    raise RuntimeError('Exceptions from {}.'.format(self)) from e
RuntimeError: Exceptions from <[8, 1, 16, 16, 16]x[8, 23, 23, 23]> ConvolveFilterAdjoint Linop>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ltorres/projects/extreme_mri/bug.py", line 22, in <module>
    device=device,
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/app.py", line 85, in run
    self.alg.update()
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/alg.py", line 63, in update
    self._update()
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/alg.py", line 414, in _update
    self.min1()
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/mri/app.py", line 336, in min_mps_ker
    show_pbar=False).run()
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/app.py", line 213, in __init__
    self._get_alg()
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/app.py", line 247, in _get_alg
    self._get_ConjugateGradient()
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/app.py", line 264, in _get_ConjugateGradient
    AHy = self.A.H(self.y)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 122, in __call__
    return self.__mul__(input)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 131, in __mul__
    return self.apply(input)
  File "/home/ltorres/anaconda3/envs/sigpyUpdated/lib/python3.7/site-packages/sigpy/linop.py", line 98, in apply
    raise RuntimeError('Exceptions from {}.'.format(self)) from e
RuntimeError: Exceptions from <[8, 16, 16, 16]x[8, 14827820]> Reshape * ConvolveFilterAdjoint * FFT * NUFFTAdjoint * Reshape * Sum * Multiply Linop>.
JsenseRecon:   0%|                                                         | 0/10 [00:01<?, ?it/s]```
```
In case it's relevant, data is non-cartesian, downsampled to fit on GPU and organized as:
```
ksp: [coils, spokes, readouts]
coord:[spokes, readouts, dimension]
dcf: [spokes, readouts]
```

Package versions:
```
cudatoolkit - 10.2.89 
cudnn - 7.6.5 
cupy - 8.0.0
numba - 0.51.2
numpy - 1.19.1
sigpy - 0.1.18/0.1.21
```

**Comment by ltorres6** [comment]
Closing. You might get this error, and potentially various other cudnn related errors if your datatypes do not match. Fixed by casting complex data to 64 bit and real data to 32 bit.

**Comment by frankong** [comment]
Cool, thanks for finding the issue
